### ISSUE TITLE
Make a gem release for forked mspec project

### ISSUE THREAD

**Issue by headius** [ruby/mspec#14]
At this point ruby/mspec has diverged just enough from rubinius/mspec (originally rubyspec/mspec) that the released mspec gem (based on rubinius/mspec) can't be used to run ruby/rubyspec anymore. Primarily, the addition of the "argf" helper prevents the specs from running green:

```
...
14)
ARGF.lines is a public method ERROR
NoMethodError: undefined method `argf' for #<Object:0xcc81cb3>
/Users/headius/projects/jruby/spec/ruby/core/argf/shared/each_line.rb:11:in `block in (root)'
org/jruby/RubyBasicObject.java:1633:in `instance_eval'
org/jruby/RubyEnumerable.java:1554:in `all?'
org/jruby/RubyFixnum.java:296:in `times'
org/jruby/RubyArray.java:1560:in `each'
/Users/headius/projects/jruby/spec/ruby/core/argf/lines_spec.rb:4:in `<top>'
org/jruby/RubyKernel.java:957:in `load'
org/jruby/RubyBasicObject.java:1633:in `instance_eval'
org/jruby/RubyArray.java:1560:in `each'
/Users/headius/projects/jruby/lib/ruby/gems/shared/gems/mspec-1.9.1/bin/mspec-ci:8:in `<top>'

15)
ARGF.lines requires multiple arguments ERROR
NoMethodError: undefined method `argf' for #<Object:0xcc81cb3>
/Users/headius/projects/jruby/spec/ruby/core/argf/shared/each_line.rb:17:in `block in (root)'
org/jruby/RubyBasicObject.java:1633:in `instance_eval'
org/jruby/RubyEnumerable.java:1554:in `all?'
org/jruby/RubyFixnum.java:296:in `times'
org/jruby/RubyArray.java:1560:in `each'
/Users/headius/projects/jruby/spec/ruby/core/argf/lines_spec.rb:4:in `<top>'
org/jruby/RubyKernel.java:957:in `load'
org/jruby/RubyBasicObject.java:1633:in `instance_eval'
org/jruby/RubyArray.java:1560:in `each'
/Users/headius/projects/jruby/lib/ruby/gems/shared/gems/mspec-1.9.1/bin/mspec-ci:8:in `<top>'
...
```

I would like to be able to set up JRuby's dev process to use a released gem rather than a vendored copy of mspec. I see a few courses of action possible:
1. Submit the argf modification to rubinius/mspec. This would allow using the mspec gem based on that repository to run ruby/rubyspec. However, it is a temporary measure as long as the ruby organization maintains a fork of mspec. There's also some chance the change would be rejected, since it is not needed by rubinius/rubyspec.
2. Release ruby/mspec as a new gem ruby-mspec (or similar name). This may lead to confusion with the existing mspec gem, but I don't think there's many projects using it.
3. Revert the argf change and return to using rubinius/mspec. This would get us back on the same page, but it limits what changes we can make to improve mspec for CRuby, JRuby, and other non-Rubinius implementations' use of it and ruby/rubyspec.

**Comment by eregon** [comment]
Could you elaborate a bit why you would like to use a released gem instead?
For instance, would a `git submodule` or some other mechanism that automatically fetches some version of ruby/mspec work or not?

I am not too fond of the argf helper, but there are quite a few other changes, some of which are bugfixes or required to run on MRI or Opal.

1. seems difficult since there are quite a few modifications, including some changes that are very unlikely to be merged.
2. I personally never used the gem, but one advantage is it would allow to easily have mspec in PATH. However, releases mean we need to carefully update versions and make sure to require a recent one enough for rubyspec. Currently the only guaranteed are "latest mspec runs latest rubyspec" and backward-compatible for the public API (but mostly I try to avoid modifying mspec).
3. Not acceptable for all changes since some of these changes are necessary.

**Comment by headius** [comment]
@eregon Less code in our repo is a good thing. I feel that we shouldn't have code in our repository that we never modify, and that definitely applies to mspec. Ok, stdlib we don't usually modify directly, but that's moving (slowly) out to gems, and we do have diffs from MRI.

`git submodule` wouldn't really change anything since we'd still have the code in our repo, never touched, never committed, manually updated.

Having ruby-mspec as a gem would mean a slightly smaller source dump as well. mspec would, like rspec, be a dev-time install.

As for versioning...it could simply be versioned based on release date (e.g. ruby-mspec-20151227 or something). I really just want something I can easily install during dev env bootstrapping and ideally run from PATH like any other Ruby dev-time tool.

Another alternative would be at least getting the gem bits in ruby/mspec usable, and moving JRuby's dev bootstrapping to a Gemfile. It could install mspec from git.

Counter questions to having "latest mspec runs latest rubyspec":

* Why maintain mspec as a separate repository at all if it is intimately tied to and only used for rubyspec?
* If it makes sense to vendor mspec, why don't we vendor rspec as well?

I agree with your assessments of my three proposals. The funny thing about all this is that the mspec gem isn't even used by rubinius...they vendor an older copy of mspec too. In fact, mspec 1.8.0, released almost a year ago, had a bug (rubinius/mspec#1) in it that prevented running rubyspec, and it was only just discovered.

**Comment by elia** [comment]
FWIW Opal already has mspec in the gemfile and it works quite well

https://github.com/opal/opal/blob/master/Gemfile

But admittedly it's probably in a different situation than jruby being a gem itself etc.

**Comment by headius** [comment]
@elia Ahh very nice! Perhaps we can modify our build to pull from github as well. I will investigate today, hopefully.

**Comment by eregon** [comment]
@headius 
> `git submodule` wouldn't really change anything since we'd still have the code in our repo, never touched, never committed, manually updated.

I think you mean `git subtree` which we use for spec/ruby (and also spec/mspec currently). I meant a `submodule` which is only a pseudo file in the jruby repo with the revision and another file saying where the repo comes from.
The sources of mspec would be downloaded by `git submodule update --init` (which could be part of the dev setup process, or the spec tasks) into spec/mspec.
It's what Opal does for rubyspec for instance: https://github.com/opal/opal/tree/master/spec
MRI does a `git clone` into the spec tasks, so essentially submodules but manually.
The Gemfile is also another abstraction on top of `git clone` in the end.

> Another alternative would be at least getting the gem bits in ruby/mspec usable, and moving JRuby's dev bootstrapping to a Gemfile. It could install mspec from git.

Feel free to edit the gemspec in this repo if needed, `ruby-mspec` is fine.

> Counter questions to having "latest mspec runs latest rubyspec":
*    Why maintain mspec as a separate repository at all if it is intimately tied to and only used for rubyspec?

Good question. I guess one answer is that it's actually used by JRuby+Truffle currently for some of its [own specs](https://github.com/jruby/jruby/tree/master/spec/truffle), because it's much lighter than RSpec and easier to get right (a test framework that is as difficult to run is not a good friend for newish implementations, although mspec is not the easiest either but at least it does not have any gem dependency nor on stdlib).
Having mspec part of the rubyspec repo could still work of course, but they seem to me two distinct pieces of software (like lib/ and spec/) and it's historic.

*    If it makes sense to vendor mspec, why don't we vendor rspec as well?

I agree it does not make sense to `vendor` in the meaning of having a full copy of the sources in another repository. No RSpec because I want something simpler and stabler for the syntax and usage.

**Comment by elia** [comment]
We too use mspec for some of our specs for the exact reason pointed out by @eregon

https://github.com/opal/opal/tree/master/spec/opal

**Comment by eregon** [comment]
@headius Did this work out with the Gemfile?

**Comment by headius** [comment]
I haven't had a change to try it :-\ There's more to it than I'd hoped since we rigged up Maven to install dependencies rather than using Bundler.

Bundler might be a smarter/simpler way to install dev-time dependencies though. What do you think, @mkristian? Should be just ditch `-Pbootstrap` and use a Gemfile for it?

**Comment by mkristian** [comment]
@headius just moving those few dev-time dependencies into Gemfile seems OK, though you need to run the tests through bundler. whether I want to dump ```-Pbootstrap``` and the travis setup, I am less sure. finally 'jruby + bundler' triggers gives a lot of pain at lookout especially with people using the latest bundler version usually, which breaks builds on a regular base.

in short I will look how easy it is to use a Gemfile with ruby-maven - I am unsure about the ```:git => ``` part, the rest is working. if this works we can ditch the bootstrap but keep the travis setup as is. and as developer you can use the usual bundler mantras.

**Comment by mkristian** [comment]
@headius just do what truffle is doing now and keep maven out of the picture for  tests. I made also an branch moving towards a Gemfile - https://github.com/jruby/jruby/tree/test-gemfile

**Comment by eregon** [comment]
This issue has been opened for a while, I want to close it.
I don't plan to make a gem release of mspec.
For starters, I'm not owner of the mspec gem and making a release every month would add significant overhead.

mspec and ruby/spec of the same time are guaranteed to work together, other combinations not.
Most of the time, newer mspec is fine but not always if there was deprecations and removals.
So please update mspec whenever ruby/spec specs are updated and all should be fine.

I'm not opposed to the idea of merging ruby/mspec in ruby/spec, but then we need to think about file structure. If you think merging the two repos would be useful, please file a new issue with a suggestion about the file structure.

**Comment by headius** [comment]
Perhaps the forked mspec should just move into ruby/spec then, since it's not being released as a standalone library.

**Comment by headius** [comment]
Oh I see that's what you meant by merging... yes, I would support that. Seems simple enough, since there's no existing lib or bin dir to conflict.

**Comment by eregon** [comment]
Right, but for example a `spec` directory under the repository root would be very confusing.
I guess we could have everything under `mspec` or so, and explicitly exclude the RSpec specs of MSpec which would be under `mspec/spec`. Still sounds kind of hacky to me.
