### ISSUE TITLE
Add guards for mswin or mingw?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/mspec#42]
With Appveyor jobs being run for both mswin & mingw, people occasionally bypass testing using:

```ruby
platform_is_not :windows
```

but the tests are only failing on one or the other, but not both.  Are there guards for mswin and mingw?

I don't know whether they should be options for `platform_is_not` or `platform_is`, but `mswin` and `mingw` are part of `RUBY_PLATFORM`...

**Comment by eregon** [comment]
I think `platform_is :mswin`/`platform_is :mingw` should work, as long as `mswin`/`mingw` are part of `RbConfig::CONFIG['host_os']`.
See the logic in https://github.com/ruby/mspec/blob/072849e769d712264e03ca4870562600775075bc/lib/mspec/guards/platform.rb#L34

@MSP-Greg Could you try it to confirm I think `platform_is :mswin` and `platform_is :mingw` work?

It seems fine to be more precise when we know only one of them fail.

Usually, I don't try too fine-grained platform guards though, because it requires a lot of time to figure out which one exactly is failing and which one not, and often the bug is due to different OS behavior.

**Comment by MSP-Greg** [comment]
@eregon

Thanks.  Rather laser focused on OpenSSL 1.1.1, I should've tried this or looked (more) at the code.  Apologies.

Anyway, you're correct, I tried in trunk, and both both `:mswin` and `:mingw` seem to work.

I tried it locally on the change in [ruby/ruby 9ab0489](https://github.com/ruby/ruby/commit/9ab04897bd06767f773b35c6958a0551981093aa#diff-04cdda67312f5090ef835be670ddf80c), as the spec file is okay on `mingw`,
